node.type.*.third_party.govcore_workflow:
  type: mapping
  label: 'GovCore Workflow settings'
  mapping:
    workflow:
      type: string
      label: 'Workflow ID'
    autosave:
      type: boolean
      label: 'Enable autosave for this content type'
